import { PropsWithChildren } from "react";
import Head from "next/head";

/**
 * Application base layout
 */
export default function XBase({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full min-h-screen w-full bg-slateGrey">
        <div className="container mx-auto">{children}</div>
      </div>
    </>
  );
}
